version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://iamuser:iampass@database/ixios_db
      - JWT_SECRET=your_secure_jwt_secret_here  # Ensure this matches the secret used in the code
      - ADMIN_EMAIL=admin@ixion.com
      - ADMIN_PASSWORD=securepassword123
      - JWT_EXPIRATION=3600
      - FLASK_DEBUG=1
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./backend:/app
    networks:
      - ixion-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - ixion-network
    
  database:
    image: postgres:16
    environment:
      - POSTGRES_USER=iamuser
      - POSTGRES_PASSWORD=iampass
      - POSTGRES_DB=ixios_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ixion-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U iamuser -d ixios_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  ixion-network:
    driver: bridge