version: '3'

services:
  database:
    image: postgres:16
    environment:
      POSTGRES_DB: ixios_db
      POSTGRES_USER: iamuser
      POSTGRES_PASSWORD: iampass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U iamuser -d ixios_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://iamuser:iampass@database/ixios_db
      - JWT_SECRET=my_secure_jwt_secret_change_in_production
      - JWT_EXPIRATION=3600
    depends_on:
      database:
        condition: service_healthy

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000
    depends_on:
      - backend

volumes:
  postgres_data: